spring:
  webmvc:
    cors:
      allowed-origins: "http://www.gestion-stock.mg"
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME:gestiondestock}?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoint:
    health:
      show-details: false

springdoc:
  swagger-ui:
    enabled: false
