spring:
  webmvc:
    cors:
      allowed-origins: "http://www.gestion-stock.mg"
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3307}/${DB_NAME:gestiondestock}?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ejb:
          interceptor: com.devtech.gestiondestock.interceptor.Interceptor

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: ${SHOW_HEALTH_DETAILS:ALWAYS}
      probes:
        enabled: true

springdoc:
  swagger-ui:
    enabled: true
server:
  port: 8080