SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE entreprise MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE utilisateur MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE category MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE client MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE fournisseur MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE article MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE vente MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE avoir MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE commande_client MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE commande_fournisseur MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE entrepot MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE facture MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE inventaire MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE ligne_commande_client MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE ligne_command_fournisseur MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE ligne_vente MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE lot MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE mvt_stk MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE paiement MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE regle_tarifaire MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE role MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE transfert_stock MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE alerte_stock MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
